#!/bin/sh

# These options are always needed.
STANDARD="-quiet -o /dev/null -nostdinc -fsyntax-only"

# Find the include path options.
INCLUDES=`
echo "" | gcc -v -x c++ -E -o /dev/null - 2>&1 |
 awk '/^\#include <.*$/   {f=1}
      /^ \/.*$/           { if (f) { printf("-I%s ",$0) } }
      /^End of search.*$/ {exit}' - | sed 's/^-I /-I/;s/ -I / -I/g'`

# See if extra -fno-honor-std is needed.
EXTRA=`
gcc --version |
  sed 's/[^0-9.]*//g' |
  awk -F "\." '{ if ($1 < 3) {printf("-fno-honor-std ") } }'`

# Find the macro definition options.
MACROS=`
echo "" |gcc -v -x c++ -E -o /dev/null - 2>&1 | sed -n '
/__GNUC__/{
  s/^.*-lang-c++ -v//
  s/ -isystem.*$//
  s/ - -o.*$//
  s/ -undef//
  s/ -A[^ ]*//g
  s/ -D\([^=]*\)=\([^ -]\{1,\} [^ -]\{1,\}\)/ -D\1='\''\2'\''/g
 p
}
'`

echo $STANDARD $MACROS $INCLUDES $EXTRA
