#!/bin/sh

# This program gets its configuration from several places.  Each has
# lower precedence than the previous.
#
#  1.) The command line:
#  2.) A configuration shell script ~/.gccxml/config is sourced.
#  3.) The environment in which this script is running.
#  4.) Automatic detection and guessing.
#
#  The settings are:
#
#   GCCXML_EXECUTABLE = The path to the real gccxml executable.
#   GCCXML_FLAGS      = The set of flags to use when running GCC-XML.
#   GCCXML_COMPILER   = The path to the compiler that GCC-XML is
#                       pretending to be.  This is used to automatically
#                       find GCCXML_FLAGS if they are not given.
#   GCCXML_USER_FLAGS = Additional flags to use when running GCC-XML.
#                       These can be set and the script will still try
#                       to detect GCCXML_FLAGS.
#
#  On the command line, use
#   "-gccxml-compiler xxx" to set "xxx" as the GCCXML_COMPILER.
#   "-gccxml-executable xxx" to set "xxx" as the GCCXML_EXECUTABLE.

# Source the config file if it exists.
if test -r ~/.gccxml/config ; then
  . ~/.gccxml/config
fi

# Use a procedure to process the command line so we don't lose our
# arguments from shift operation.
gccxml_processCommandLine()
{
  GCCXML_ARGUMENTS=""
  while test "x$1" != "x" ; do
    if test "$1" = "-gccxml-compiler" ; then
      GCCXML_COMPILER="$2"
      shift ; shift
    elif test "$1" = "-gccxml-executable" ; then
      GCCXML_EXECUTABLE="$2"
      shift ; shift
    else
      GCCXML_ARGUMENTS="${GCCXML_ARGUMENTS} $1"
      shift
    fi
  done
}

gccxml_processCommandLine $@

# The real gccxml executable is located next to this script.
SELFPATH=`echo $0 | sed -n '/\//{s/\/gccxml//;p;}'`
if test "x$SELFPATH" = "x" ; then SELFPATH="." ; fi
SELFPATH=`cd $SELFPATH ; pwd`

# Find the gccxml_cc1plus executable.
if test "x$GCCXML_EXECUTABLE" = "x" ; then
  if test -x "${SELFPATH}/gccxml_cc1plus" ; then
    GCCXML_EXECUTABLE="${SELFPATH}/gccxml_cc1plus"
  else
    echo "Cannot find gccxml_cc1plus executable."
    exit 1
  fi
fi

# Find the gccxml flags script.
if test "x$GCCXML_FLAGS" = "x" ; then
  if test -x "${SELFPATH}/gccxml_find_flags" ; then
    GCCXML_FIND_FLAGS="${SELFPATH}/gccxml_find_flags"
  elif test -x "${SELFPATH}/../share/GCC_XML/gccxml_find_flags" ; then
    GCCXML_FIND_FLAGS="${SELFPATH}/../share/GCC_XML/gccxml_find_flags"
  else
    echo "Cannot find GCC_XML flags script gccxml_find_flags."
    exit 1
  fi
  if ! GCCXML_FLAGS=`${GCCXML_FIND_FLAGS} ${GCCXML_COMPILER}` ; then
    echo "Error executing gccxml_find_flags script:"
    echo ${GCCXML_FLAGS}
    exit 1
  fi
fi

# Check if we were given any arguments.
if test "x${GCCXML_ARGUMENTS}" = "x" ; then
  echo "No arguments given.  Not running GCC-XML executable."
  exit 1
fi

# Run the GCC-XML executable.
${GCCXML_EXECUTABLE} ${GCCXML_FLAGS} ${GCCXML_USER_FLAGS} ${GCCXML_ARGUMENTS}
