#!/bin/sh

# These options are always needed.
STANDARD="-quiet -o /dev/null -nostdinc -I- -w -fsyntax-only"

# Find the macro definition options.
MACROS=`
echo "" | gcc -v -x c++ -E ${CXXFLAGS} -o /dev/null - 2>&1 |
sed -n '/__GNUC__/{s/ -/\\
-/g;p;}' |
sed -n '/^-D.*$/{s/-D\([^=]*\)=\([^ ]\{1,\} .*\)/-D\1='\''\2'\''/;p;}' |
sed -n 'H;${g;s/\n/ /g;p;}'`

# Find the include path options.
INCLUDES=`
echo "" | gcc -v -x c++ -E ${CXXFLAGS} -o /dev/null - 2>&1 |
awk '/^\#include <.*$/   {f=1}
     /^ \/.*$/           { if (f) { printf("-I%s ",$0) } }
     /^End of search.*$/ {exit}' - | sed 's/^-I /-I/;s/ -I / -I/g'`

# The support headers are located where this script is.
SELFPATH=`echo $0 | sed -n '/\//{s/\/find_gcc_options$//;p;}'`
if test "x$SELFPATH" = "x" ; then SELFPATH="." ; fi
SELFPATH=`cd $SELFPATH ; pwd`
INCLUDES="-I$SELFPATH $INCLUDES"

# See if extra -fno-honor-std is needed.
EXTRA=`
gcc --version |
sed 's/[^0-9.]*//g' |
awk -F "\." '{ if ($1 < 3) {printf("-fno-honor-std ") } }'`

# Format and print out the options.
OPTIONS="$STANDARD $MACROS $INCLUDES $EXTRA"
echo $OPTIONS
