#!/bin/sh

# Find the GCC executable name.
if test "x$1" = "x" ; then
  if test "x${CXX}" = "x" ; then
    CXX=gcc
  fi
else 
  CXX=$1
fi

# These options are always needed.
STANDARD="-quiet -o /dev/null -w -fsyntax-only -nostdinc "

# Find the macro definition options.
MACROS=`
echo "" | ${CXX} -v -x c++ -E ${CXXFLAGS} -o /dev/null - 2>&1 |
sed -n '/__GNUC__/{s/ -/\\
-/g;p;}' |
sed -n '/^-D.*$/{s/-D\([^=]*\)=\([^ ]\{1,\} .*\)/-D\1='\''\2'\''/;p;}' |
sed -n 'H;${g;s/\n/ /g;p;}'`

# Find the include path options.
INCLUDES=`
echo "" | ${CXX} -v -x c++ -E ${CXXFLAGS} -o /dev/null - 2>&1 |
awk '/^\#include <.*$/   {f=1}
     /^ \/.*$/           { if (f) { printf("-I%s ",$0) } }
     /^End of search.*$/ {exit}' - | sed 's/^-I /-I/;s/ -I / -I/g'`

# The support headers are located where this script is.
SELFPATH=`echo $0 | sed -n '/\//{s/\/find_gcc_options$//;p;}'`
if test "x$SELFPATH" = "x" ; then SELFPATH="." ; fi
SELFPATH=`cd $SELFPATH ; pwd`

# Determine the major version number.
MAJOR_VERSION=`
${CXX} --version |
sed 's/[^0-9.]*//g' |
awk -F "\." '{ print $1 }'`

# For GCC versions before 3, some special options are needed.
if test $MAJOR_VERSION -lt 3 ; then
  HONOR_STD="-fxml-no-honor-std "
  STRICT_INCLUDES="-I- "
  INCLUDES="-I$SELFPATH $INCLUDES"
fi

# Format and print out the options.
OPTIONS="$STANDARD $STRICT_INCLUDES $MACROS $INCLUDES $HONOR_STD"
echo $OPTIONS
