#!/bin/sh
# Installation script for GCC compiler support headers and programs.

. install_helper

install_directory "GccInclude" "" "find_gcc_options"
install_directory "GccInclude/std" "complext.h" ""

