#!/bin/sh
# Installation script for GCC compiler support headers and programs.

. $2/install_helper

install_directory "GccInclude" "" "find_gcc_options"
install_directory "GccInclude/2_95/std" "complext.h" ""

