#!/bin/sh

# Find the MIPSPro executable name.
if test "x$1" = "x" ; then
  if test "x${CXX}" = "x" ; then
    CXX=CC
  fi
else 
  CXX=$1
fi

# These options are always needed.
STANDARD="-quiet -o /dev/null -nostdinc -I- -w -fsyntax-only"

GCCXML_PID="$$"
touch /tmp/find_mpro_options_temp$GCCXML_PID.cxx

# Find the macro definition options.
MACROS=`
${CXX} ${CXXFLAGS} -E -v /tmp/find_mpro_options_temp$GCCXML_PID.cxx 2>&1 |
sed -n '/_COMPILER_VERSION/{s/ \/tmp\/find_mpro_options_temp$GCCXML_PID.cxx.*$//
s/ -/\\
-/g;p;}' |
sed -n '/^-D.*$/{s/-D\([^=]*\)=\([^ ]\{1,\} .*\)/-D\1='\''\2'\''/;p;}' |
sed -n 'H;${g;s/\n/ /g;p;}'`

# Find and translate the -LANG:std option into -D_STANDARD_C_PLUS_PLUS
LANGSTD=`
${CXX} ${CXXFLAGS} -E -v /tmp/find_mpro_options_temp$GCCXML_PID.cxx 2>&1 |
sed -n '/_COMPILER_VERSION/{s/ \/tmp\/find_mpro_options_temp$GCCXML_PID.cxx.*$//
s/ -/\\
-/g;p;}' |
sed -n '/^-LANG:std.*$/{s/-LANG:std/-D_STANDARD_C_PLUS_PLUS/;p;}' |
sed -n 'H;${g;s/\n/ /g;p;}'`

# Find the include path options.
INCLUDES=`
${CXX} ${CXXFLAGS} -E -v /tmp/find_mpro_options_temp$GCCXML_PID.cxx 2>&1 |
sed -n '/_COMPILER_VERSION/{s/ \/tmp\/find_mpro_options_temp$GCCXML_PID.cxx.*$//
s/ -/\\
-/g;p;}' |
sed -n '/^-I.*$/{p;}' |
sed -n 'H;${g;s/\n/ /g;p;}'`

# The support headers are located where this script is.
SELFPATH=`echo $0 | sed -n '/\//{s/\/find_mpro_options$//;p;}'`
if test "x$SELFPATH" = "x" ; then SELFPATH="." ; fi
SELFPATH=`cd $SELFPATH ; pwd`
INCLUDES="-I$SELFPATH/7_3 $INCLUDES"

rm -f /tmp/find_mpro_options_temp$GCCXML_PID.cxx

# Format and print out the options.
OPTIONS="$STANDARD $MACROS $LANGSTD $INCLUDES"
echo $OPTIONS
