#!/bin/sh
# Installation script for MipsPro compiler support headers and programs.

. $2/install_helper

install_directory "MproInclude" "" "find_mpro_options"

install_directory "MproInclude/7_3" \
  "stddef.h stl_config.h stl_monetary.h stl_threads.h ostream
   stl_locale.h stl_numeric_facets.h string" ""
